### ISSUE TITLE
KISS principle violation

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#1]
in your main export you have a big `switch()` with no other code around it. 

https://github.com/kaskadi/kaskadi-stock-update-lambda/blob/b6fae1e31400837a1c920d11eaaf100f297e15e8/kaskadi-stock-update-lambda.js#L7

this suggests that you basically have two different functions that do two completely different things...

```
module.exports.handler = async (event) => {
  const eventSource = getLambdaEventSource(event)
  let warehouses
  switch (eventSource) {
    case 'api':
     // do one thing
    case 'scheduled':
      // do something completely different
    default:
      break
  }
}
```

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

No more `switch` :smile: 

Closing for now.
