### ISSUE TITLE
productData._source.stocks is an array

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#10]
https://github.com/kaskadi/kaskadi-stock-update-lambda/blob/b6fae1e31400837a1c920d11eaaf100f297e15e8/helpers/update-product-stocks.js#L12

isn't  `productData._source.stocks` already an Array? no need to spread that to a new Array, right?

so just:
```
let stocks = productData._source.stocks.map(stock => {
    if (stock.warehouse === warehouse) {
      return {
        warehouse: stock.warehouse,
        ...stockData
      }
    }
    return stock
  })
```

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

With refactoring this code doesn't exist anymore :smile: 
I think I did it initially because I had a first approach with `push` to build my new array so I didn't want to modify the original one but that was a silly decision anyway...

Closing for now!
