### ISSUE TITLE
Updates post refactoring review

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#12]
because there is no PR i will comment here

**Comment by Holger-Will** [comment]
`invokeStockUpdate` is not a good description of what the function does. sure a function is invoked, no need to tell it again. following the other naming (`getStockData`) you could name it `setStockData`, maybe?

**Comment by Holger-Will** [comment]
remove the comment from the code... these comments could be in a PR, not permanently in the code ...

**Comment by Holger-Will** [comment]
move this line to `getStockData`
https://github.com/kaskadi/kaskadi-get-ysws-stocks-lambda/blob/c93677b5b14b17ddc54b0587a8ea2791ac7cc42b/kaskadi-get-ysws-stocks-lambda.js#L16

**Comment by Holger-Will** [comment]
```
setStockData( getStockData( fromDate ) )
```
... 
make `getStockData()` return nothing when there is no stock updated...
then in `setStockData()` you can just `if(stock) invoke...`

**Comment by alexlemaire** [comment]
Same as for the other issue: I handled poorly the PR

Will work on those updates!

**Comment by alexlemaire** [comment]
Updated, check [here](https://github.com/kaskadi/kaskadi-get-ysws-stocks-lambda/commit/1af5b9e9b38db0906dcfcdc06045312881c7da36#commitcomment-37721928) for extra details

There are only 2 commits for this update (one being minor fix) so you can comment directly on the commit if you want!

**Comment by Holger-Will** [comment]
commenting on commits is not optimal... please always go for PRs, please

**Comment by alexlemaire** [comment]
> commenting on commits is not optimal... please always go for PRs, please

Alright will build the habit from now on then :+1:
