### ISSUE TITLE
use `availableStock()`

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#2]
Wemalo API has an endpoint that returns all stocks that change since a given date...

> availableStock
> Loads available stock since date by attribute. All products that have stock changes in the given timeframe will be reported back.

use that instead of looping over all items and call the api for each one...

http://connect-api.wemalo.com/#api-Product-availableStock

**Comment by Holger-Will** [comment]
using this, we get one Array of items and changed stock info with just one call.
then we could use ES batch update feature to update all products in ES with one call...

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#_bulk

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

Done. `kaskadi-get-ysws-stocks-lambda` uses `availableStock()` to get stock info.

Closing for now.
