### ISSUE TITLE
listing warehouses should not be necessary

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#7]
listing warehouses should not be necessary. We do not want to poll all warehouses at the same interval, and so the logic of always looping over all warehouses is broken...

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

No more listing of all warehouses. The lambda only deals with getting stocks info from YSWS and triggering another lambda to do the update in our DB.

Closing for now.
