### ISSUE TITLE
use a map instead of an array

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#9]
for the storage of stock data in ES we currently use an array. i think most of the current issues stem from that fact that we use an Array as a data structure... we might want to switch to using a map.

so instead of 

```
stocks:[
  {
    warehouse: "ysws",
    state: "new",
    amount: 10
  },
  {
    warehouse: "amz_de",
    state: "new",
    amount: 10
  },
]
```
we should realy use
```
stocks:{
  ysws: {
    amount: 10
  },
  amz_de: {
    amount: 10
  },
]
```
that way we can simply do partial updates without having to fetch the documents first!

**Comment by Holger-Will** [comment]
i'm still not sure how to handle different states (quality of items like "used", "refurbished" etc.)

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

Done!

Closing for now, we can open a new issue regarding handling of product states if we need :-)
